export const DEMO_CASES = [
  // ─── TEXT + VIDEO ADS ─────────────────────────────────────────────

  {
    id: 1,
    title: "Pearson: Failure Is Not an Option",
    description: "Classic text-heavy education ad. High clarity, zero visual flair — pure copy test.",
    headline: "FAILURE IS NOT AN OPTION",
    body: "NOVANET Essay Contest. I Did It! Pearson Education.",
    platform: "Meta",
    type: "text",
    industry: "education",
    audience: "Students",
    hashtags: ["#Education", "#NOVANET", "#EssayContest", "#Pearson"],
    placements: ["Feed", "Right Column"],
    geo: "US",
    landingUrl: "https://www.pearson.com",
    competitor: "Chegg, McGraw-Hill, Coursera",
    cpc: 1.10,
    budget: 15000,
  },
  {
    id: 2,
    title: "Liquid Death: Big Game Commercial",
    description: "Anti-marketing water brand. Kids hydrating at a party like it's a beer ad. Subversive humor.",
    url: "https://www.youtube.com/watch?v=qQwt4rzmVxY",
    localAsset: "/demos/liquid_death.mp4",
    headline: "MURDER YOUR THIRST",
    body: "Don't be scared. It's just water. Liquid Death Mountain Water. Don't be scared, it's just water.",
    platform: "Meta",
    type: "video",
    industry: "e-commerce",
    audience: "Gen-Z (18-24)",
    hashtags: ["#LiquidDeath", "#MurderYourThirst", "#BigGame", "#DontBeScared"],
    placements: ["Reels", "Feed", "Stories"],
    geo: "US",
    landingUrl: "https://www.liquiddeath.com",
    competitor: "Topo Chico, Prime Hydration, Essentia, VOSS",
    cpc: 0.42,
    budget: 8000000,
  },
  {
    id: 3,
    title: "Apple: Clean Up Photos",
    description: "Sleek product demo. Apple Intelligence AI feature showcase for iPhone 16 — minimal, aspirational.",
    url: "https://www.youtube.com/watch?v=iL88A5F9V3k",
    localAsset: "/demos/apple_intel.mp4",
    headline: "Apple Intelligence",
    body: "Clean Up. Remove distractions from your photos with a tap. Apple Intelligence on iPhone 16.",
    platform: "Google",
    type: "video",
    industry: "technology",
    audience: "Tech Enthusiasts",
    hashtags: ["#AppleIntelligence", "#iPhone16", "#CleanUp", "#ShotOniPhone"],
    placements: ["YouTube Pre-roll", "Discovery"],
    geo: "US",
    landingUrl: "https://www.apple.com/apple-intelligence/",
    competitor: "Samsung Galaxy AI, Google Pixel, Microsoft Copilot",
    cpc: 2.80,
    budget: 25000000,
  },
  {
    id: 4,
    title: "Joe's Coffee (Generic SMB)",
    description: "Over-the-top hyperbolic local cafe ad. All buzzwords, no substance — a weak-ad baseline.",
    headline: "THE WORLD'S BEST COFFEE",
    body: "Come down to Joe's. We have the world's best coffee. Premium beans. Expert baristas. Guaranteed satisfaction. Open 7 days.",
    platform: "Meta",
    type: "text",
    industry: "e-commerce",
    audience: "Foodies",
    hashtags: ["#Coffee", "#CoffeeShop", "#LocalBusiness"],
    placements: ["Feed", "Marketplace"],
    geo: "US",
    landingUrl: "https://www.joescoffee.com",
    competitor: "Starbucks, Dunkin', Blue Bottle, Peet's",
    cpc: 0.55,
    budget: 500,
  },
  {
    id: 5,
    title: "NikeSKIMS: Bodies at Work ft. LISA",
    description: "Premium fashion-athletic collab. Spring '26 with BLACKPINK's LISA — high production, global reach.",
    url: "https://www.youtube.com/watch?v=9q636eA-KsQ",
    localAsset: "/demos/skims_shorts.mp4",
    headline: "NikeSKIMS Spring '26",
    body: "Bodies at work. The NikeSKIMS Spring '26 Collection featuring LISA. Designed for movement. Built for everything in between.",
    platform: "Meta",
    type: "video",
    industry: "e-commerce",
    audience: "Luxury Buyers",
    hashtags: ["#NikeSKIMS", "#LISA", "#BodiesAtWork", "#Spring26"],
    placements: ["Reels", "Stories", "Feed"],
    geo: "US",
    landingUrl: "https://www.nikeskims.com",
    competitor: "Lululemon, Alo Yoga, Gymshark, Fabletics",
    cpc: 0.78,
    budget: 12000000,
  },
  {
    id: 6,
    title: "Patagonia: Don't Buy This Jacket",
    description: "Iconic anti-consumerist campaign. High cultural resonance, sustainability messaging.",
    headline: "DON'T BUY THIS JACKET",
    body: "This Black Friday, we're asking you to consider the environmental cost of everything you buy, including our own products. Reduce. Repair. Reuse. Recycle.",
    platform: "Meta",
    type: "text",
    industry: "e-commerce",
    audience: "Eco-Conscious",
    hashtags: ["#Patagonia", "#DontBuyThisJacket", "#BlackFriday", "#Sustainability"],
    placements: ["Feed", "Stories"],
    geo: "US",
    landingUrl: "https://www.patagonia.com/stories/dont-buy-this-jacket/",
    competitor: "North Face, Arc'teryx, REI, Columbia",
    cpc: 1.20,
    budget: 750000,
  },
  {
    id: 7,
    title: "Tesla: Optimus Gen 2",
    description: "Official robotics demo. Futuristic humanoid robot showcase — technical credibility play.",
    url: "https://www.youtube.com/watch?v=cpraXaw7dyc",
    localAsset: "/demos/tesla_optimus.mp4",
    headline: "Optimus Gen 2",
    body: "Optimus — Gen 2. Faster. More precise. Fully autonomous humanoid robot. The future of labor, built by Tesla.",
    platform: "Google",
    type: "video",
    industry: "technology",
    audience: "Tech Enthusiasts",
    hashtags: ["#Tesla", "#Optimus", "#Gen2", "#Robotics", "#AI"],
    placements: ["YouTube Pre-roll", "Discovery", "Display"],
    geo: "US",
    landingUrl: "https://www.tesla.com/optimus",
    competitor: "Boston Dynamics, Figure AI, Agility Robotics, Sanctuary AI",
    cpc: 2.10,
    budget: 3000000,
  },

  // ─── LINKEDIN DEMOS (4 tiers of quality) ──────────────────────────

  {
    id: 8,
    title: "LinkedIn: PLG Thought Leadership",
    description: "Data-driven strategic post. High-authority voice, strong hook, industry-specific insights.",
    headline: "The ROI of Product-Led Growth in 2026",
    body: "We analyzed 340 SaaS companies over 3 years. Companies investing in PLG see 2.5x higher net revenue retention vs. sales-led peers.\n\nThe pattern is clear: lower CAC, faster expansion, stickier users.\n\nBut here's what nobody talks about — PLG fails without a strong data team. You can't optimize what you can't measure.\n\nFull breakdown in the comments. What's your experience?",
    platform: "LinkedIn",
    type: "text",
    postType: "article",
    followerCount: 12500,
    industry: "technology",
    audience: "Professionals",
    hashtags: ["#SaaS", "#ProductLedGrowth", "#GrowthStrategy", "#B2BMarketing", "#StartupMetrics"],
    placements: ["Feed"],
    geo: "US",
    landingUrl: "https://openviewpartners.com/plg-index",
    competitor: "HubSpot, Salesforce, Gainsight",
    cpc: 5.80,
    budget: 25000,
  },
  {
    id: 9,
    title: "LinkedIn: Engineering Hiring Post",
    description: "Standard culture + hiring post. Decent hook but generic messaging — mid-tier engagement.",
    headline: "We're growing! Join our Engineering team.",
    body: "Building the future of AI infrastructure is not easy, but our team makes it look fun. We just shipped our v3 platform in 11 weeks.\n\nNow we need 3 more senior engineers who care about reliability at scale.\n\nRemote-first. Competitive comp. Real problems.\n\nDM me or apply at the link below 👇",
    platform: "LinkedIn",
    type: "text",
    postType: "image",
    followerCount: 2100,
    industry: "b2b",
    audience: "Professionals",
    hashtags: ["#Hiring", "#EngineeringJobs", "#RemoteWork", "#TechCulture", "#StartupLife"],
    placements: ["Feed", "Sponsored Message"],
    geo: "US",
    landingUrl: "https://careers.example.com/engineering",
    competitor: "Greenhouse, Lever, Ashby",
    cpc: 4.20,
    budget: 5000,
  },
  {
    id: 10,
    title: "LinkedIn: Q3 Corporate Update",
    description: "Dry corporate boilerplate. No hook, no story, no humanity — the anti-engagement post.",
    headline: "Q3 Stakeholder Update",
    body: "We are pleased to announce our Q3 results were in line with expectations. Revenue was $14.2M, up 3% YoY. We continue to execute against our strategic roadmap and look forward to updating shareholders in Q4.",
    platform: "LinkedIn",
    type: "text",
    postType: "text",
    followerCount: 850,
    industry: "finance",
    audience: "Professionals",
    hashtags: ["#Q3Results", "#Earnings", "#CorporateUpdate"],
    placements: ["Feed"],
    geo: "US",
    landingUrl: "https://ir.example.com/q3-2026",
    competitor: "Bloomberg Terminal, Refinitiv, S&P Capital IQ",
    cpc: 6.50,
    budget: 2000,
  },
  {
    id: 11,
    title: "LinkedIn: AI Hot Take (Viral Bait)",
    description: "High-risk contrarian opinion. Designed to spark debate — engagement farming meets real insight.",
    headline: "Why 90% of AI Startups Will Fail by 2027",
    body: "The wrapper era is over.\n\nI've reviewed 200+ pitch decks this quarter. 80% are thin GPT wrappers with no defensible moat.\n\nThe survivors will be companies that own their data, their inference stack, or their distribution. Everyone else is renting from OpenAI.\n\nHarsh? Maybe. But VCs aren't writing checks for 'we fine-tuned Llama' anymore.\n\nWhat's your take — agree or disagree?",
    platform: "LinkedIn",
    type: "text",
    postType: "poll",
    followerCount: 45000,
    industry: "technology",
    audience: "Tech Enthusiasts",
    hashtags: ["#AI", "#Startups", "#VentureCapital", "#HotTake", "#AIStartups"],
    placements: ["Feed"],
    geo: "US",
    landingUrl: "",
    competitor: "Y Combinator, a16z, Sequoia",
    cpc: 3.90,
    budget: 0,
  },

  // ─── VIDEO DEMOS (user-specified URLs) ────────────────────────────

  {
    id: 12,
    title: "Bridgerton × Marketplace: Regency Riders",
    description: "Meta's own Bridgerton S4 partnership ad. Regency-era characters browse Facebook Marketplace. Premium cultural moment marketing.",
    url: "https://www.youtube.com/shorts/NheTktcB2Fo",
    localAsset: "/demos/bridgerton_1.mp4",
    headline: "For Every Listing, There's A Story",
    body: "Yearning to make your Regency debut? Shop Bridgerton-inspired finds worthy of a most-public display of commitment. Available on Facebook Marketplace. Search 'Bridgerton' for access.",
    platform: "Meta",
    type: "video",
    industry: "e-commerce",
    audience: "Millennials (25-39)",
    hashtags: ["#Bridgerton", "#FacebookMarketplace", "#RegencyEra", "#NetflixPartner", "#ShopTheLook"],
    placements: ["Reels", "Stories", "Feed"],
    geo: "US",
    landingUrl: "https://www.facebook.com/marketplace",
    competitor: "eBay, Poshmark, Depop, Etsy",
    cpc: 0.85,
    budget: 2500000,
  },
  {
    id: 13,
    title: "Bridgerton × Marketplace: Shop Regency",
    description: "Second creative cut of the Bridgerton S4 × Facebook Marketplace campaign. Different pacing, same cultural moment.",
    url: "https://www.youtube.com/shorts/MKN1iYybItY",
    localAsset: "/demos/bridgerton_2.mp4",
    headline: "Shop Regency on Facebook Marketplace",
    body: "Facebook Marketplace presents: Bridgerton. From carriages to corsets, every listing tells a story. Season 4, Part 1 now streaming on Netflix.",
    platform: "Meta",
    type: "video",
    industry: "e-commerce",
    audience: "Parents",
    hashtags: ["#Bridgerton", "#ShopRegency", "#Marketplace", "#NetflixXMeta", "#BridgertonSeason4"],
    placements: ["Feed", "Reels", "Stories"],
    geo: "US",
    landingUrl: "https://www.facebook.com/marketplace",
    competitor: "Poshmark, Mercari, ThredUp, OfferUp",
    cpc: 0.92,
    budget: 2500000,
  },
  {
    id: 14,
    title: "Coinbase: Everybody",
    description: "Mass-market crypto adoption play. Backstreet Boys-style jingle parody. Super Bowl energy, mainstream positioning.",
    url: "https://www.youtube.com/watch?v=ox__f7ZdFyM",
    localAsset: "/demos/coinbase.mp4",
    headline: "Crypto is for Everybody",
    body: "Oh my god, we're back again. Am I the original crypto exchange? Am I the only financial app you need? Am I so secure? Crypto is for Everybody. Coinbase.",
    platform: "Google",
    type: "video",
    industry: "finance",
    audience: "Millennials (25-39)",
    hashtags: ["#Coinbase", "#Crypto", "#Bitcoin", "#CryptoForEverybody", "#FinTech"],
    placements: ["YouTube Pre-roll", "Discovery", "Display"],
    geo: "US",
    landingUrl: "https://www.coinbase.com",
    competitor: "Binance, Kraken, Gemini, Robinhood Crypto",
    cpc: 3.20,
    budget: 5000000,
  },
  {
    id: 15,
    title: "Anthropic: Keep Thinking",
    description: "Anti-advertising positioning. 'Ads are coming to AI. But not to Claude.' Bold trust-building against monetized AI competitors.",
    url: "https://www.youtube.com/watch?v=De-_wQpKw0s",
    localAsset: "/demos/anthropic.mp4",
    headline: "Keep Thinking",
    body: "What do you think of my business idea? Ads are coming to AI. But not to Claude. Keep thinking.",
    platform: "Google",
    type: "video",
    industry: "technology",
    audience: "Tech Enthusiasts",
    hashtags: ["#Claude", "#Anthropic", "#AI", "#KeepThinking", "#NoAdsInAI"],
    placements: ["YouTube Pre-roll", "Discovery"],
    geo: "US",
    landingUrl: "https://www.anthropic.com/news/claude-is-a-space-to-think",
    competitor: "OpenAI, Google Gemini, Microsoft Copilot, Perplexity AI",
    cpc: 4.50,
    budget: 1500000,
  },
];